<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<?xml-stylesheet ekr_test ?>
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="leo.20160425104942.1"><vh>因為位於 users/s2a/g100 目錄, 必須跳三層才到外圍</vh></v>
<v t="leo.20160425104947.1"><vh>@path ./../../../</vh>
<v t="leo.20160425104947.2" a="E"><vh>假如要送到 gh-pages 分支, 使用下列按鈕</vh>
<v t="leo.20160425104947.3"><vh>@button gh-pages pelican</vh></v>
</v>
<v t="leo.20160425104947.4" a="E"><vh>假如要在近端檢視, 使用下列按鈕</vh>
<v t="leo.20160425104947.5"><vh>@button local pelican</vh></v>
</v>
<v t="leo.20160425104947.6"><vh>進入 content 目錄</vh></v>
<v t="leo.20160425104947.7" a="E"><vh>@path content</vh>
<v t="leo.20160425104947.8" a="E"><vh>@path ag6</vh>
<v t="leo.20160425104947.9"><vh>@clean ag6_40323112.md</vh></v>
<v t="leo.20160425104947.10"><vh>@clean ag6_40323133.md</vh></v>
<v t="leo.20160425104947.11"><vh>@clean ag6_40323147.md</vh></v>
<v t="leo.20160425104947.12"><vh>@clean ag6_40323152.md</vh></v>
<v t="leo.20160425104947.13"><vh>@clean ag6_40323155.md</vh></v>
<v t="leo.20160425104947.14"><vh>@clean ag6_40323156.md</vh></v>
</v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="leo.20160425104942.1"></t>
<t tx="leo.20160425104947.1"></t>
<t tx="leo.20160425104947.10">@language md
Title: 40323133-期中報告
Category: ag6
Tags: scrum2, task1
Author: kmol
@others
2D繪圖Openshift連結: &lt;a href="http://40323133-ag6.rhcloud.com/ag6/task1"&gt;http://40323133-2ag6.rhcloud.com/ag6/task1&lt;/a&gt;


協同用程式碼A: &lt;a href="http://40323133-2ag6.rhcloud.com/ag6_40323133/A"&gt;http://40323133-2ag6.rhcloud.com/ag6_40323133/A&lt;/a&gt;

協同用程式碼B: &lt;a href="http://40323133-2ag6.rhcloud.com/ag6_40323133/B"&gt;http://40323133-2ag6.rhcloud.com/ag6_40323133/B&lt;/a&gt;

協同用程式碼C: &lt;a href="http://40323133-2ag6.rhcloud.com/ag6_40323133/C"&gt;http://40323133-2ag6.rhcloud.com/ag6_40323133/C&lt;/a&gt;

協同用程式碼D: &lt;a href="http://40323133-2ag6.rhcloud.com/ag6_40323133/D"&gt;http://40323133-2ag6.rhcloud.com/ag6_40323133/D&lt;/a&gt;


3D繪圖Onshape連結: &lt;a href="https://cad.onshape.com/documents/0a1d746bb64b17bf4a43bf78"&gt;https://cad.onshape.com/documents/0a1d746bb64b17bf4a43bf78&lt;/a&gt;
</t>
<t tx="leo.20160425104947.11">@language md
Title: 40323147-期中報告
Category: ag6
Tags: scrum2, task1
Author: kmol
@others
2D繪圖Openshift連結: &lt;a href="http://40323147-ag6.rhcloud.com/ag6/task1"&gt;http://40323147-2ag6.rhcloud.com/ag6/task1&lt;/a&gt;


協同用程式碼A: &lt;a href="http://40323147-2ag6.rhcloud.com/ag6_40323147/A"&gt;http://40323147-2ag6.rhcloud.com/ag6_40323147/A&lt;/a&gt;

協同用程式碼B: &lt;a href="http://40323147-2ag6.rhcloud.com/ag6_40323147/B"&gt;http://40323147-2ag6.rhcloud.com/ag6_40323147/B&lt;/a&gt;

協同用程式碼C: &lt;a href="http://40323147-2ag6.rhcloud.com/ag6_40323147/C"&gt;http://40323147-2ag6.rhcloud.com/ag6_40323147/C&lt;/a&gt;

協同用程式碼D: &lt;a href="http://40323147-2ag6.rhcloud.com/ag6_40323147/D"&gt;http://40323147-2ag6.rhcloud.com/ag6_40323147/D&lt;/a&gt;


3D繪圖Onshape連結: &lt;a href="https://cad.onshape.com/documents/0a1d746bb64b17bf4a43bf78"&gt;https://cad.onshape.com/documents/0a1d746bb64b17bf4a43bf78&lt;/a&gt;
</t>
<t tx="leo.20160425104947.12">@language md
Title: 40323252-期中報告
Category: ag6
Tags: scrum2, task1
Author: kmol
@others
2D繪圖Openshift連結: &lt;a href="http://40323152-ag6.rhcloud.com/ag6/task1"&gt;http://40323152-ag6.rhcloud.com/ag6/task1&lt;/a&gt;


協同用程式碼A: &lt;a href="http://40323152-ag6.rhcloud.com/ag6_40323152/A"&gt;http://40323152-ag6.rhcloud.com/ag6_40323152/A&lt;/a&gt;

協同用程式碼B: &lt;a href="http://40323152-ag6.rhcloud.com/ag6_40323152/B"&gt;http://40323152-ag6.rhcloud.com/ag6_40323152/B&lt;/a&gt;

協同用程式碼C: &lt;a href="http://40323152-ag6.rhcloud.com/ag6_40323152/C"&gt;http://40323152-ag6.rhcloud.com/ag6_40323152/C&lt;/a&gt;

協同用程式碼D: &lt;a href="http://40323152-ag6.rhcloud.com/ag6_40323152/D"&gt;http://40323152-ag6.rhcloud.com/ag6_40323152/D&lt;/a&gt;


3D繪圖Onshape連結: &lt;a href="https://cad.onshape.com/documents/0a1d746bb64b17bf4a43bf78"&gt;https://cad.onshape.com/documents/0a1d746bb64b17bf4a43bf78&lt;/a&gt;

</t>
<t tx="leo.20160425104947.13">@language md
Title: 40323155-期中報告
Category: ag6
Tags: scrum2, task1
Author: kmol
@others
2D繪圖Openshift連結: &lt;a href="http://40323155-ag6.rhcloud.com/ag6/task1"&gt;http://40323155-ag6.rhcloud.com/ag6/task1&lt;/a&gt;


協同用程式碼A: &lt;a href="http://40323155-ag6.rhcloud.com/ag6_40323155/A"&gt;http://40323155-ag6.rhcloud.com/ag6_40323155/A&lt;/a&gt;

協同用程式碼B: &lt;a href="http://40323155-ag6.rhcloud.com/ag6_40323155/B"&gt;http://40323155-ag6.rhcloud.com/ag6_40323155/B&lt;/a&gt;

協同用程式碼C: &lt;a href="http://40323155-ag6.rhcloud.com/ag6_40323155/C"&gt;http://40323155-ag6.rhcloud.com/ag6_40323155/C&lt;/a&gt;

協同用程式碼D: &lt;a href="http://40323155-ag6.rhcloud.com/ag6_40323155/D"&gt;http://40323155-ag6.rhcloud.com/ag6_40323155/D&lt;/a&gt;


3D繪圖Onshape連結: &lt;a href="https://cad.onshape.com/documents/0a1d746bb64b17bf4a43bf78"&gt;https://cad.onshape.com/documents/0a1d746bb64b17bf4a43bf78&lt;/a&gt;
</t>
<t tx="leo.20160425104947.14">@language md
Title: 40323156-期中報告
Category: ag6
Tags: scrum2, task1
Author: kmol
@others

2D繪圖Openshift連結: &lt;a href="http://40323156-ag6.rhcloud.com/ag6/task1"&gt;http://40323156-ag6.rhcloud.com/ag6/task1&lt;/a&gt;


協同用程式碼A: &lt;a href="http://40323156-ag6.rhcloud.com/ag6_40323156/A"&gt;http://40323156-ag6.rhcloud.com/ag6_40323156/A&lt;/a&gt;

協同用程式碼B: &lt;a href="http://40323156-ag6.rhcloud.com/ag6_40323156/B"&gt;http://40323156-ag6.rhcloud.com/ag6_40323156/B&lt;/a&gt;

協同用程式碼C: &lt;a href="http://40323156-ag6.rhcloud.com/ag6_40323156/C"&gt;http://40323156-ag6.rhcloud.com/ag6_40323156/C&lt;/a&gt;

協同用程式碼D: &lt;a href="http://40323156-ag6.rhcloud.com/ag6_40323156/D"&gt;http://40323156-ag6.rhcloud.com/ag6_40323156/D&lt;/a&gt;


3D繪圖Onshape連結: &lt;a href="https://cad.onshape.com/documents/0a1d746bb64b17bf4a43bf78"&gt;https://cad.onshape.com/documents/0a1d746bb64b17bf4a43bf78&lt;/a&gt;

</t>
<t tx="leo.20160425104947.2"></t>
<t tx="leo.20160425104947.3">@language python
import os
os.system("pelican content -o post -s publishconf.py")
g.es("admin pelican 執行完畢")

</t>
<t tx="leo.20160425104947.4"></t>
<t tx="leo.20160425104947.5">@language python
import os
#os.system("pelican content -o output -s local_publishconf.py -t theme/pelican-bootstrap3")
os.system("pelican content -o post -s local_publishconf.py")
g.es("admin pelican 近端執行完畢")


</t>
<t tx="leo.20160425104947.6"></t>
<t tx="leo.20160425104947.7"></t>
<t tx="leo.20160425104947.8"></t>
<t tx="leo.20160425104947.9">@language md
Title: 40323112-期中報告
Category: ag6
Tags: scrum2, task1
Author: kmol
@others
2D繪圖Openshift連結: &lt;a href="http://40323112-ag6.rhcloud.com/ag6/task1"&gt;http://40323112-2ag6.rhcloud.com/ag6/task1&lt;/a&gt;


協同用程式碼A: &lt;a href="http://40323112-2ag6.rhcloud.com/ag6_40323112/A"&gt;http://40323112-2ag6.rhcloud.com/ag6_40323112/A&lt;/a&gt;

協同用程式碼B: &lt;a href="http://40323112-2ag6.rhcloud.com/ag6_40323112/B"&gt;http://40323112-2ag6.rhcloud.com/ag6_40323112/B&lt;/a&gt;

協同用程式碼C: &lt;a href="http://40323112-2ag6.rhcloud.com/ag6_40323112/C"&gt;http://40323112-2ag6.rhcloud.com/ag6_40323112/C&lt;/a&gt;

協同用程式碼D: &lt;a href="http://40323112-2ag6.rhcloud.com/ag6_40323112/D"&gt;http://40323112-2ag6.rhcloud.com/ag6_40323112/D&lt;/a&gt;


3D繪圖Onshape連結: &lt;a href="https://cad.onshape.com/documents/0a1d746bb64b17bf4a43bf78"&gt;https://cad.onshape.com/documents/0a1d746bb64b17bf4a43bf78&lt;/a&gt;</t>
</tnodes>
</leo_file>
